create extension if not exists vector;

create table if not exists documents (
    id bigint generated by default as identity primary key,
    filename text not null,
    file_hash text not null unique,
    created_at timestamptz not null default now()
);

create table if not exists chunks (
    id bigint generated by default as identity primary key,
    document_id bigint not null references documents(id) on delete cascade,
    filename text not null,
    page_number integer not null,
    chunk_index integer not null,
    content text not null,
    embedding vector(384) not null,
    created_at timestamptz not null default now()
);

create index if not exists chunks_document_id_idx on chunks(document_id);
create index if not exists chunks_embedding_hnsw_idx
    on chunks using hnsw (embedding vector_cosine_ops);

create or replace function match_chunks(
    query_embedding vector(384),
    match_document_ids bigint[],
    match_count integer default 5
)
returns table (
    id bigint,
    document_id bigint,
    filename text,
    page_number integer,
    chunk_index integer,
    content text,
    similarity real
)
language sql
stable
as $$
    select
        chunks.id,
        chunks.document_id,
        chunks.filename,
        chunks.page_number,
        chunks.chunk_index,
        chunks.content,
        (1 - (chunks.embedding <=> query_embedding))::real as similarity
    from chunks
    where chunks.document_id = any(match_document_ids)
    order by chunks.embedding <=> query_embedding
    limit greatest(match_count, 1);
$$;
